version: '3.1'

services:
  db:
    image: "postgres:alpine"
    volumes:
      - .db:/var/lib/postgresql/data

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"



  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: .env
    depends_on:
      - db
      - broker
      - result

  celery:
    build:
      dockerfile: Dockerfile
      context: .
    command: python manage.py celery
    volumes:
      - ./obytesproject/:/home/user/app/
    env_file: .env
    depends_on:
      - db
      - broker
      - result
