version: '3.1'

services:
  db:
    image: "postgres:alpine"
    volumes:
      - .db:/var/lib/postgresql/data

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"



  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/user/app/
    env_file: .env
    depends_on:
      - db
      - broker
      - result

  celery:
    build:
      dockerfile: Dockerfile
      context: .
    command: celery -A obytesproject worker -l info -B
    volumes_from:
      - web
    env_file: .env
    depends_on:
      - db
      - broker
      - result
